name = "wg-const-eval"
subteam-of = "compiler"
wg = true

[people]
leads = ["oli-obk", "RalfJung"]
members = [
    "ecstatic-morse",
    "oli-obk",
    "RalfJung",
]

[website]
name = "Compile-time function evaluation"
description = "Expanding the capabilities of compile-time function evaluation in Rust"
repo = "https://github.com/rust-lang/const-eval"

[github]
orgs = ["rust-lang", "rust-lang-nursery"]
